
# colours
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)

SCALE = 32

SCREEN_HEIGHT = 480
SCREEN_WIDTH = 640

MAP_TILE_GRASS = "G"
MAP_TILE_ROADNORTH = "R"
MAP_TILE_ROADEAST = "P"
MAP_TILE_CORNERDOWNRIGHT = "C"
MAP_TILE_CORNERDOWNLEFT = "U"
MAP_TILE_CORNERUPRIGHT = "D"
MAP_TILE_CORNERUPLEFT = "E"
MAP_TILE_WATER = "W"
MAP_TILE_BRIDGE = "B"
MAP_TILE_SAND = "S"
MAP_TILE_GROUNDSWAP = "A"
MAP_TILE_ROADSWAP = "F"
MAP_TILE_SANDROADNORTH = "H"